name: melos_test

packages:
  - apps/**
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
  pubget:
    name: pub get
    description: Run pub get
    run: flutter pub get
    exec:
      concurrency: 1

command:
  bootstrap:
    hooks:
      pre: echo '---- Pre-bootstrap ----'
      post: echo '---- Post-bootstrap ----'
  version:
    branch: main